language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t vkuzm/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true vkuzm/docker-react npm run test a -- --watchAll=false --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react2"
    env: "DockerReact2-env"
    bucket_name: "elasticbeanstalk-us-east-1-964176841427"
    bucket_path: "docker-react"
    on:
        branch: main
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
